### ISSUE TITLE
Issue on page /12_image_analysis_basics/02_Working_with_images.html - data

### ISSUE THREAD

**Issue by ElisabethKugler** [haesleinhuepf/BioImageAnalysisNotebooks#12]
Hey @haesleinhuepf,

working through the section "12_image_analysis_basics/02_Working_with_images" I found the "blobs.tif" using Fiji, but I am not sure where I would find the dataset "banana020.tif" for the exercise?
Have I missed any links to data? 

Thank you for the fantastic course.

Eli

**Comment by haesleinhuepf** [comment]
Hi Eli @ElisabethKugler ,

the image is located here: https://github.com/haesleinhuepf/BioImageAnalysisNotebooks/blob/main/data/banana/banana0020.tif

In the course we use this exercise indeed to make the students search for data in the repository and teach them the concepts of folders and paths. But I agree, a hint would make sense there to make the reader search in the right directory.

Thanks for the feedback!

Robert

**Comment by ElisabethKugler** [comment]
Many thanks for the swift reply @haesleinhuepf!

Ah, yes I think it would be good to just hint people to the fact that these notebooks are built on a course as well as image.sc discussions. e.g. "Looking for things" and "discussing solutions" is part of this :) 
I was naturally looking for it in Fiji (as for blobs and hela-cells), so maybe just a hint for the banana file would be enough.

Thanks!
