### ISSUE TITLE
How do PRs work to notebooks?

### ISSUE THREAD

**Issue by psobolewskiPhD** [haesleinhuepf/BioImageAnalysisNotebooks#13]
Sorry for the stupid question, but I can't figure this out.
How does making a PR to a notebook work?
I can edit and change a code cell, but what about the output?

**Comment by haesleinhuepf** [comment]
You find the explanation how to edit the chapters here:
https://github.com/haesleinhuepf/BioImageAnalysisNotebooks#bio-image-analysis-notebooks
Let me know tyou need anything else!

**Comment by psobolewskiPhD** [comment]
I saw that, but still don't quite get it—sorry!
So I install all the stuff...
Then make a fork to clone and make a branch?
*Then* edit a cell...
and *then build* using the .build.sh?
Or do I build before branching?
I need a branch to make a PR, right?
(The curse of notebooks is this complexity right? can't just use the GitHub pencil ✏️ for simple stuff)

**Comment by haesleinhuepf** [comment]
You do not need to build. But yes, you should install everything (jupyter in particular) to edit the notebook. If you change code, you should execute the whole notebook. If you just fix a typo in the text(sorry about all the typos), it might not be necessary.

But running the notebooks is fun btw! They should all execute on your computer.

**Comment by psobolewskiPhD** [comment]
> If you change code, you should execute the whole notebook. 

The issue is a colormap (`jet` bad! use `turbo` or `inferno` https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html) so re-rendering the images is kinda the key.
So fork, clone, install, branch, edit cells, then run notebook, then commit and PR?

> But running the notebooks is fun btw! They should all execute on your computer.

I know! I've run a few of them, just copy-pasta into my VS Code environment and playing with parameters.

**Comment by haesleinhuepf** [comment]
> So fork, clone, install, branch, edit cells, then run notebook, then commit and PR?

Yes. It sounds more complicated than it is though
