### ISSUE TITLE
napari and nD visualization

### ISSUE THREAD

**Issue by guiwitz** [haesleinhuepf/BioImageAnalysisNotebooks#19]
The chapter "Image visualization in 3D" actually presents  nD visualization cases rather than just 3D. Should it be renamed? Also the [notebook on napari](https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/16_3d_image_visualization/05_napari.html) only uses the blobs image and the explanations are quite limited. Should this notebook be extended and improved? Also this notebook is a bit redundant with the one presented in the [GUI chapter](https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/31_graphical_user_interfaces/napari.html). Should just one be kept? And should there be one notebook that explains all basic ideas of napari or would this be redundant with other tutorials/resources? I sort of like the idea to have all minimum material in one place but that's of course up for debate.

**Comment by haesleinhuepf** [comment]
It's tricky indeed. Maybe we can move the basics for visualization (including napari) into a `visualization` chapter and additionally have the more advanced stuff in the `GUI` folder? I'm also not exactly sure about where to draw the red line though...
