### ISSUE TITLE
Issue on page /18_image_filtering/03_background_removal.html

### ISSUE THREAD

**Issue by Nelson-Gon** [haesleinhuepf/BioImageAnalysisNotebooks#22]
Hi, 

Thank you for these notes. I noticed a minor (furthermore) typo in this sentence

"There are other techniques for background subtraction such as the [top-hat](https://scikit-image.org/docs/dev/auto_examples/applications/plot_morphology.html#white-tophat). **Furthwermore,** the [Difference of Gaussians (DoG)](https://scikit-image.org/docs/stable/auto_examples/filters/plot_dog.html) is a technique for combined denoising and background removal."

More interestingly, would it be possible to add some benchmarks regarding how fast different algorithms are? This could be useful to devs interested in fast yet good enough implementations. Also, perhaps a table with a few cons/pros of different algorithms might be useful.

Apologies if these are tackled elsewhere and I do appreciate this awesome work.

NelsonGon

**Comment by haesleinhuepf** [comment]
Awesome! Thanks for the feedback @Nelson-Gon . I'm going to fix it soon. Some notebooks were written in a rush and that's why feedback of that kind is extremely helpful.

Thanks again and Happy New Year!
