### ISSUE TITLE
Navbar not working on iPad in portrait mode

### ISSUE THREAD

**Issue by iimog** [haesleinhuepf/BioImageAnalysisNotebooks#34]
I'm mainly reading the notebooks on my iPad in portrait mode. A couple of weeks ago, the navbar stopped working. When I click on the icon at the top left, the screen turns dim but the navbar does not open. It works in landscape mode, in the browser and on my phone. But I'm able to reproduce the problem in Firefox Mobile view (Ctrl+Shift+M) when selecting iPad there.

<img src="https://github.com/haesleinhuepf/BioImageAnalysisNotebooks/assets/7403236/42005af1-ed2d-4267-8ec5-8687f9ee1569" width="40%"/>
<img src="https://github.com/haesleinhuepf/BioImageAnalysisNotebooks/assets/7403236/f1a1af63-1619-4484-b724-aac1290db213" width="40%"/>

I tracked the issue down to this commit: https://github.com/haesleinhuepf/BioImageAnalysisNotebooks/commit/2cd4c3583aa28d29176a7f441dc488a1eb9af040
Indeed, when upgrading to `sphinx-book-theme` version 1.0.1 the sidebar works on my iPad. However, the search icon is back in the middle, rather than the navbar.

**Comment by iimog** [comment]
In the current `sphinx-book-theme` version 1.1.3 the search bar is back in the sidenav. The overall layout and design looks very similar when updating. And the navbar also works again on the iPad. You might consider removing the restriction of `sphinx-book-theme` to versions before 1.0.0. Below is a screenshot of the page with the new version.
![image](https://github.com/user-attachments/assets/800ade86-ecff-42b5-bd4e-c60476ae4d77)

**Comment by haesleinhuepf** [comment]
> Below is a screenshot of the page with the new version

Wow cool! Can you please send this as pull-request? I would love to merve it!

**Comment by iimog** [comment]
With pleasure.

These notebooks are such a great resource. I used some of their content for teaching a course twice, and I regularly refer students here. I'm very happy to contribute some minor improvements, particularly as this project is managed in such a welcoming way. :smiley:
