### ISSUE TITLE
add notebook demonstrating the difference between `cle.scale` and `skimage.transform.downscale_local_mean`

### ISSUE THREAD

**Issue by thawn** [haesleinhuepf/BioImageAnalysisNotebooks#39]
cle.skale essentially preserves noise when downscaling. [skimage.transform.downscale_local_mean](https://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.downscale_local_mean), on the other hand, denoises at the same time.

I would like to add a notebook that demonstrates this.

**Comment by thawn** [comment]
Just give me a few days ...

**Comment by haesleinhuepf** [comment]
Maybe compare https://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.rescale instead of/and `cle.scale`.
