### ISSUE TITLE
Issue on page layouts

### ISSUE THREAD

**Issue by kephale** [haesleinhuepf/BioImageAnalysisNotebooks#43]
Hey @haesleinhuepf 

Low priority issue, but when I try to browse the notebooks on a widescreen monitor that is rotated (e.g. tall and narrow), the table of contents panel on the left hand side does not show up. Moving the browser to a monitor with widescreen orientation reveals the table of contents.

Cheers,
Kyle

P.S. very happy to see you get new awesome opportunities in Leipzig :)

**Comment by iimog** [comment]
This might be related to #34 - you can try if it is also fixed with the latest `sphinx-book-theme` version 1.1.3.

**Comment by haesleinhuepf** [comment]
I'm just posting a comparison of the old and the new layout here:

![image](https://github.com/user-attachments/assets/96e678b9-030f-4af2-b1bc-5eef9055b6ec)

@kephale is your issue solved in the current version?

**Comment by kephale** [comment]
@haesleinhuepf Yeah, its working on my setup! I'll close the issue.
