### ISSUE TITLE
Immunofluorescence data 

### ISSUE THREAD

**Issue by apal6** [haesleinhuepf/BioImageAnalysisNotebooks#45]
Hi,

Thank you for the wonderful tutorial. I am working on some immunofluorescence data and this is my first time looking at it, would be great if you could provide some insights on my workflow.  I am doing this to quantify immune cells (three channels corresponds to three stains) in the biopsy samples. 
I have three channels and DAPI. I am trying to run your notebook for cell segmentation in one of the channel image to look at the stained cells. Some caveats, my files are RGB instead of the CMY on QuPath, I wonder what difference would it make? 
Should I be using overlaid image (which has all three colors) or individual tiff files? 

I basically loaded my tif files and ran the commands from [https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/20b_deep_learning/cellpose.html]. 

Would appreciate any suggestions. 

Thank you!

**Comment by haesleinhuepf** [comment]
Hi @apal6 ,

that's not my core expertise unfortunately. I recommend reaching out to the bio-image analysis experts on https://image.sc . They are a very friendly community. Also consider sharing example data and screenshots to make it easier to support you.

Best,
Robert
